spring:
  application:
    name: bank-investment-risk-system

  datasource:
    url: jdbc:mysql://localhost:3306/bankrisk?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.SnakeCasePhysicalNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 2000ms

  mail:
    host: smtp.163.com
    port: 587
    username: your-email@163.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.xingye.bankrisk: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# JWT配置
jwt:
  secret: mySecretKey12345678901234567890123456789012345678901234567890
  expiration: 86400000  # 24小时，单位毫秒

# 文件上传配置
file:
  upload:
    max-size: 10MB
    temp-dir: uploads/temp/

# 工作流配置
workflow:
  stages:
    - JUNIOR
    - MID
    - SENIOR
    - COMMITTEE
  timeouts:
    junior: 2  # 小时
    mid: 4
    senior: 8
    committee: 24

# 风险评估配置
risk:
  assessment:
    conservative:
      score-range: "0-30"
      products: ["CASH", "BOND"]
    moderate:
      score-range: "31-70"
      products: ["BOND", "ETF", "STOCK"]
    aggressive:
      score-range: "71-100"
      products: ["STOCK", "ALT", "COMMODITY"]
